language: node_js
node_js:
  - 0.8
before_script:
  coffee --compile -o
before_install:
  - npm install coffeescript

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master