// Generated by CoffeeScript 2.5.0
var map_create;

import {
  TileTypes
} from './enums.js';

map_create = function(pillars) {
  var coords, i, j, k, l, len, m, new_map, x, y;
  //new_map = [[ get_index(TileTypes.FLOOR) for _ in range(0, constants.MAP_HEIGHT)] for _ in range(0, constants.MAP_WIDTH)]
  new_map = [];
  for (x = i = 0; i <= 20; x = ++i) {
    new_map.push([]);
    for (y = j = 0; j <= 20; y = ++j) {
      new_map[x].push([TileTypes.FLOOR]);
    }
  }
  for (k = 0, len = pillars.length; k < len; k++) {
    coords = pillars[k];
    new_map[coords[0]][coords[1]] = TileTypes.WALL; //.block_path = True
  }

  // walls around the map
  for (x = l = 0; l <= 20; x = ++l) {
    new_map[x][0] = TileTypes.WALL; //.block_path = True
    new_map[x][19] = TileTypes.WALL; //.block_path = True
  }
  for (y = m = 0; m <= 20; y = ++m) {
    new_map[0][y] = TileTypes.WALL; //.block_path = True
    new_map[19][y] = TileTypes.WALL; //.block_path = True
  }
  return new_map;
};

export {
  map_create
};
