// Generated by CoffeeScript 2.5.0
var DeathProcessor;

import {
  Name,
  Dead,
  Player
} from './components.js';

import {
  State
} from './js_game_vars.js';

DeathProcessor = class DeathProcessor {
  
    constructor() {
      this.world = undefined
    }
    // constructor ->
    //     @world = undefined
    //     @action = null
    ;

  process() {
    var comps, dead, ent, i, len, name, ref;
    ref = this.world.get_components(Name, Dead);
    //console.log ("Death processor...")
    for (i = 0, len = ref.length; i < len; i++) {
      [ent, comps] = ref[i];
      //console.log "Dead... " + ent
      [name, dead] = comps;
      if (this.world.component_for_entity(ent, Player)) {
        State.messages.push(["You are DEAD!", [255, 0, 0]]);
        // skip
        continue;
      }
      State.messages.push([name.name + " is dead!", [127, 127, 127]]);
      // delete from ECS
      this.world.delete_entity(ent); // avoid coffeescript's implicit return
    }
  }

};

export {
  DeathProcessor
};
