// Generated by CoffeeScript 2.5.0
var FovProcessor, block_sight, explore, init_FOV, init_explored, transparent, update_FOV;

import {
  Player,
  Position
} from './components.js';

import {
  PermissiveFov
} from './ppfov/index.js';

import {
  TileTypes
} from './enums.js';

import {
  State
} from './js_game_vars.js';

explore = function(x, y) {
  State.fov[x][y] = 1;
  State.explored[x][y] = 1;
};

//console.log State.explored[x][y]
block_sight = function(x, y) {
  return TileTypes.data[State.map[x][y]].block_path;
};

transparent = function(x, y) {
  return !block_sight(x, y);
};

init_FOV = function() {
  var fov, i, j, x, y;
  fov = [];
  for (x = i = 0; i <= 20; x = ++i) {
    fov.push([]);
    for (y = j = 0; j <= 20; y = ++j) {
      fov[x].push([0]);
    }
  }
  return fov;
};

init_explored = function() {
  var explored, i, j, x, y;
  explored = [];
  for (x = i = 0; i <= 20; x = ++i) {
    explored.push([]);
    for (y = j = 0; j <= 20; y = ++j) {
      explored[x].push([0]);
    }
  }
  return explored;
};

update_FOV = function(src_x, src_y, fov_ob) {
  var i, j, x, y;
  // Generate FOV
  //game_vars.fov = [[0 for _ in range(constants.MAP_HEIGHT)] for _ in range(constants.MAP_WIDTH)]
  // Clear
  State.fov = [];
  for (x = i = 0; i <= 20; x = ++i) {
    State.fov.push([]);
    for (y = j = 0; j <= 20; y = ++j) {
      State.fov[x].push([0]);
    }
  }
  fov_ob.compute(src_x, src_y, 6, explore);
};

FovProcessor = class FovProcessor {
  
    constructor(fov_ob) {
      this.world = undefined;
      this.fov_ob = fov_ob;
    }
    ;

  process() {
    var comps, ent, i, len, player, pos, ref, results;
    ref = this.world.get_components(Player, Position);
    results = [];
    for (i = 0, len = ref.length; i < len; i++) {
      [ent, comps] = ref[i];
      [player, pos] = comps;
      //print("FOV process pos " + str(pos.x) + " " + str(pos.y))
      results.push(update_FOV(pos.x, pos.y, this.fov_ob));
    }
    return results;
  }

};

export {
  FovProcessor,
  init_FOV,
  init_explored,
  explore,
  block_sight,
  transparent,
  update_FOV
};
