// Generated by CoffeeScript 2.5.0
var tiles_distance_to;

tiles_distance_to = function(start, target) {
  var x_diff, y_diff;
  x_diff = start[0] - target[0];
  y_diff = start[1] - target[1];
  //#ensure always positive values
  if (x_diff < 0) {
    x_diff = x_diff * -1;
  }
  if (y_diff < 0) {
    y_diff = y_diff * -1;
  }
  return Math.max(x_diff, y_diff);
};

export {
  tiles_distance_to
};
