// Generated by CoffeeScript 2.5.0
var get_free_tiles, random_free_tile, tiles_distance_to;

import {
  TileTypes
} from './enums.js';

import {
  State
} from './js_game_vars.js';

get_free_tiles = function(inc_map) {
  var free_tiles, i, j, max_x, max_y, ref, ref1, x, y;
  free_tiles = [];
  max_y = inc_map[0].length - 1;
  max_x = inc_map.length - 1;
  for (y = i = 0, ref = max_y; (0 <= ref ? i <= ref : i >= ref); y = 0 <= ref ? ++i : --i) {
    for (x = j = 0, ref1 = max_x; (0 <= ref1 ? j <= ref1 : j >= ref1); x = 0 <= ref1 ? ++j : --j) {
      if (!TileTypes.data[inc_map[x][y]].block_path) {
        free_tiles.push([x, y]);
      }
    }
  }
  return free_tiles;
};

random_free_tile = function(inc_map) {
  var free_tiles, index, tile, x, y;
  free_tiles = get_free_tiles(inc_map);
  index = State.rng.range(0, free_tiles.length - 1);
  //console.log("Index is " + index)
  x = free_tiles[index][0];
  y = free_tiles[index][1];
  console.log("Coordinates are " + x + " " + y);
  tile = [x, y];
  return tile;
};

tiles_distance_to = function(start, target) {
  var x_diff, y_diff;
  x_diff = start[0] - target[0];
  y_diff = start[1] - target[1];
  //#ensure always positive values
  if (x_diff < 0) {
    x_diff = x_diff * -1;
  }
  if (y_diff < 0) {
    y_diff = y_diff * -1;
  }
  return Math.max(x_diff, y_diff);
};

export {
  tiles_distance_to,
  random_free_tile
};
