// Generated by CoffeeScript 2.5.1
var struc_Tile;

struc_Tile = class struc_Tile {
  constructor(name, map_str, block_path, color = [255, 255, 255]) {
    this.name = name;
    this.map_str = map_str;
    this.block_path = block_path;
    this.color = color;
  }

};

export {
  struc_Tile
};
